from tkinter import *
from tkinter.font import BOLD
boobalan=Tk()
boobalan.title("boobalan")
boobalan.geometry("1080x600")
center_name=Label(boobalan,text="BIKE SERVICE CENTER",font=("times",25,BOLD),fg="red")
center_name.grid()
name=Label(boobalan,text="Name",font=("times",15,BOLD),fg="green")
name.grid(row=1,column=0)
nameentry=Entry(boobalan,font=("times",15,BOLD),fg="green")
nameentry.grid(row=1,column=1)
vehiclename=Label(boobalan,text="vehicle name",font=("times",15,BOLD),fg="green")
vehiclename.grid(row=2,column=0)
v_enrry=Entry(boobalan,font=("times",15,BOLD),fg="green")
v_enrry.grid(row=2,column=1)
v_number=Label(boobalan,text="vehicle number",font=("times",15,BOLD),fg="green")
v_number.grid(row=3,column=0)
v_numberentry=Entry(boobalan,font=("times",15,BOLD),fg="green")
v_numberentry.grid(row=3,column=1)
mobile=Label(boobalan,text="mobile",font=("times",15,BOLD),fg="green")
mobile.grid(row=4,column=0)
mob=Entry(boobalan,font=("times",15,BOLD),fg="green")
mob.grid(row=4,column=1)
adr=Label(boobalan,text="address",font=("times",15,BOLD),fg="green")
adr.grid(row=5,column=0)
ad=Entry(boobalan,font=("times",15,BOLD),fg="green")
ad.grid(row=5,column=1)
amount=Label(boobalan,text="service amount",font=("times",15,BOLD),fg="green")
amount.grid(row=6,column=0)
amd=Entry(boobalan,font=("times",15,BOLD),fg="green")
amd.grid(row=6,column=1)
save=Button(boobalan,text="save",bg="green",fg="white")
save.grid(row=7,column=0)
delete=Button(boobalan,text="delete",bg="red",fg="white")
delete.grid(row=7,column=1)
clear=Button(boobalan,text="clear",bg="black",fg="white")
clear.grid(row=7,column=2)
edit=Button(boobalan,text="edit",bg="pink",fg="white")
edit.grid(row=7,column=3)
show=Button(boobalan,text="show",bg="yellow",fg="white")
show.grid(row=7,column=4)
boobalan.mainloop()